#!/bin/bash
echo "============================================="
echo "  TensorFlow GPU Container - Optimized Image"
echo "============================================="
echo "GPU Status:"
python -c "import tensorflow as tf; print(f\"GPUs: {tf.config.list_physical_devices('GPU')}\")" || echo "GPU check failed!"
echo ""
echo "Mount Points:"
echo "  - /workspace/data     (for datasets)"
echo "  - /workspace/models   (for saved models)" 
echo "  - /workspace/notebooks (for Jupyter notebooks)"
echo ""
echo "Health Check:"
echo "  This container includes a health check that verifies GPU availability"
echo "  every 5 minutes instead of the default 30 seconds."
echo ""
echo "System Monitoring:"
echo "  - Type 'htop' to monitor CPU & memory usage"
echo "  - Type 'gpumon' to monitor GPU usage with nvidia-smi"
echo "  - Type 'nvidia-smi' for a one-time GPU status check"
echo "  - Press 'q' to exit htop or Ctrl+C to exit gpumon"
echo "============================================="
exec "$@"