#!/bin/bash
echo "============================================="
echo "  TensorFlow GPU Container - Optimized Image"
echo "============================================="
echo "GPU Status:"
python -c "import tensorflow as tf; print(f\"GPUs: {tf.config.list_physical_devices('GPU')}\")" || echo "GPU check failed!"
echo ""
echo "Mount Points:"
echo "  - /workspace/data     (for datasets)"
echo "  - /workspace/models   (for saved models)" 
echo "  - /workspace/notebooks (for Jupyter notebooks)"
echo ""
echo "Health Check:"
echo "  This container includes an automatic health check"
echo "  that verifies GPU availability every 30 seconds."
echo ""
echo "System Monitoring:"
echo "  Type 'btop' to launch the system monitor"
echo "  Press 'q' to exit btop"
echo "============================================="
exec "$@"